spring.application.name=CDSmarkazTelegramBot

spring.datasource.url=jdbc:postgresql://localhost:5432/cdsmarkazbot
spring.datasource.username=postgres
spring.datasource.password=IzIb030305
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=mening-maxfiy-kalitim-kamida-32-belgi-bolishi-kerak-12345
jwt.expiration = 9000000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.org.springframework.security=DEBUG
ftp.server=127.0.0.1
ftp.port=21
ftp.username=ibrohim7
ftp.password=7777
ftp.remote-dir=/ftp/files/